---
title: "lab5_Hyejoo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# US confirmed case bar plot : June VS September
```{r}
Confirmed_State_6_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>%
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```
```{r}
Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```

```{r}
str(Confirmed_State_6_13)
str(Confirmed_State_9_13)
```

```{r}
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_6_13_9_13_joined)
```

```{r}
which(is.na(Confirmed_State_6_13_9_13_joined))
```
```{r}
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_6_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y)
head(Confirmed_State_6_13_9_13_joined)
```

```{r}
which(is.na(Confirmed_State_6_13_9_13_joined))
```

```{r, fig.width = 7, fig.height = 10}
Confirmed_State_6_13_9_13_joined_long <- Confirmed_State_6_13_9_13_joined %>% 
  pivot_longer(-c(Province_State),
               names_to = "Date", values_to = "Confirmed")
ggplot(Confirmed_State_6_13_9_13_joined_long, aes(x = Confirmed, y = Province_State)) + 
  geom_bar(stat = 'identity', color = "black", aes(fill = Date))+ 
  labs(title = "US COVID-19 Confirmed Cases",
       subtitle = "June VS September",
       x = "Confirmed Cases", 
       y = "State") +  
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5))
```

## Worldwide Deaths per day
```{r}
time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
time_series_deaths_long <- time_series_deaths %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long), names_to = "Date", values_to = "Deaths")
```

```{r}
library(lubridate)
```

```{r}
time_series_deaths_long$Date <- mdy(time_series_deaths_long$Date)
```

```{r}
deaths_worldwide <- time_series_deaths_long %>% 
  group_by(Date) %>% 
  summarise_at(c("Deaths"), sum)
ggplot(deaths_worldwide, aes(Date, Deaths, group = 1)) + 
  geom_point() + 
  geom_line() + 
  labs(x = "Date", y = "Deaths", title = "COVID-19 Deaths Worldwide")
```

## Death per Confirmed cases US

```{r}
time_series_confirmed <- read_csv("data/time_series_covid19_confirmed_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
time_series_confirmed_long <- time_series_confirmed %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long), names_to = "Date", values_to = "Confirmed")
time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
```
```{r}
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)
```

```{r}
time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
              select(-Key)
which(is.na(time_series_long_joined$Deaths))
which(is.na(time_series_long_joined$Confirmed))
```
```{r}
head(time_series_long_joined)
```

```{r}
time_series_long_joined_plus <- time_series_long_joined %>% 
  mutate(Deaths_per_Confirmed = Deaths/Confirmed)
time_series_long_joined_plus$Deaths_per_Confirmed[is.nan(time_series_long_joined_plus$Deaths_per_Confirmed)] <- 0
```

```{r}
time_series_long_joined_counts <- time_series_long_joined_plus %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```

```{r}
time_series_long_joined_plus$Date <- mdy(time_series_long_joined_plus$Date)
```

```{r}
time_series_long_joined_plus %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths", "Deaths_per_Confirmed"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths_per_Confirmed)) + 
    geom_point() +
    geom_line() + 
    ggtitle("US COVID-19 Deaths per Confirmed Cases")
```

## Top 10 Countires for Deaths

```{r}
library(tidyverse)
library(DT)
```


```{r}
time_series_top_10 <- time_series_long_joined_plus %>% 
  group_by(Country_Region) %>% 
  summarize(Confirmed = sum(Confirmed),
            Deaths = sum(Deaths),
            Deaths_per_Confirmed = sum(Deaths_per_Confirmed))%>% 
  arrange(desc(Deaths)) %>% 
  slice(1:10)
datatable(time_series_top_10)
```

```{r}
time_series_long_joined_plus %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths", "Deaths_per_Confirmed"), sum) %>% 
  filter(Country_Region %in% c("US", "Brazil", "United Kingdom", "Italy", "Mexico", "India", "France", "Spain", "Iran", "Peru")) %>% 
  ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
  geom_point() + 
  geom_line() + 
  ggtitle("Top 10 Death Countries: COVID-19 Deaths")
```


